### ISSUE TITLE
Cannot install in osmc 2019.11-1 - Raspberry 2

### ISSUE THREAD

**Issue by rimugu** [osmc/rtl8812au-osmc#2]
osmc@osmc:~/rtl8812au-osmc/rtl8812au$ sudo make -f Makefile.dkms install
make clean
make[1]: Entering directory '/home/osmc/rtl8812au-osmc/rtl8812au'
make ARCH=arm CROSS_COMPILE= -C /home/osmc/rtl8812au-osmc/rtl8812au/../../../../ M=/home/osmc/rtl8812au-osmc/rtl8812au clean
make[2]: Entering directory '/'
make[2]: *** No rule to make target 'clean'.  Stop.
make[2]: Leaving directory '/'
Makefile:1606: recipe for target 'clean' failed
make[1]: *** [clean] Error 2
make[1]: Leaving directory '/home/osmc/rtl8812au-osmc/rtl8812au'
Makefile.dkms:11: recipe for target 'src_install' failed
make: *** [src_install] Error 2
osmc@osmc:~/rtl8812au-osmc/rtl8812au$ sudo apt-get install linux-image-rpi-rpfv linux-headers-rpi-rpfv dkms build-essential bc
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-image-rpi-rpfv
E: Unable to locate package linux-headers-rpi-rpfv
osmc@osmc:~/rtl8812au-osmc/rtl8812au$ uname -a
Linux osmc 4.19.55-6-osmc #1 SMP PREEMPT Sun Nov 3 22:15:28 UTC 2019 armv7l GNU/Linux
osmc@osmc:~/rtl8812au-osmc/rtl8812au$ cat /etc/debian_version
9.11
osmc@osmc:~/rtl8812au-osmc/rtl8812au$ cat /etc/os-release
PRETTY_NAME="Open Source Media Center"
NAME="OSMC"
VERSION="November 2019"
VERSION_ID="2019.11-1"
ID=osmc
ID_LIKE=debian

ANSI_COLOR="1;31"
HOME_URL="https://www.osmc.tv"
SUPPORT_URL="https://www.osmc.tv"
BUG_REPORT_URL="https://www.osmc.tv"
osmc@osmc:~/rtl8812au-osmc/rtl8812au$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : BCM2835
Revision        : a01041
Serial          : 00000000b4360e39
osmc@osmc:~/rtl8812au-osmc/rtl8812au$

**Comment by samnazarko** [comment]
Hi,

DKMS is not supported at this time.
Have a look at how I have implemented it in kernel-osmc.

RTL will likely come back soon; but I don't want to get hopes up
